export default {

  FILES_RECEIVED: 'FILES_RECEIVED',
  FILE_CREATED: 'FILE_CREATED',
	PROFILES_RECEIVED: 'PROFILES_RECEIVED',
  PROFILE_CREATED:'PROFILE_CREATED',
  PROFILE_RECEIVED: 'PROFILE_RECEIVED',
  USER_LOGGED_IN: 'USER_LOGGED_IN'

}
